package com.onslyde.domain;

// Generated May 15, 2012 3:25:29 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Attendee generated by hbm2java
 */
@Entity
@Table(name = "attendee", catalog = "onslyde")
public class Attendee implements java.io.Serializable {

	private Integer id;
	private String ip;
	private String name;
	private String email;
	private String socketId;
	private Set<SlideGroupVotes> slideGroupVoteses = new HashSet<SlideGroupVotes>(0);

	public Attendee() {
	}

	public Attendee(String ip, String name, String email, String socketId,
			Set<SlideGroupVotes> slideGroupVoteses) {
		this.ip = ip;
		this.name = name;
		this.email = email;
		this.socketId = socketId;
		this.slideGroupVoteses = slideGroupVoteses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "ip", length = 20)
	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "email")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "socket_id")
	public String getSocketId() {
		return this.socketId;
	}

	public void setSocketId(String socketId) {
		this.socketId = socketId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "attendee")
	public Set<SlideGroupVotes> getSlideGroupVoteses() {
		return this.slideGroupVoteses;
	}

	public void setSlideGroupVoteses(Set<SlideGroupVotes> slideGroupVoteses) {
		this.slideGroupVoteses = slideGroupVoteses;
	}

}
