package com.onslyde.domain;

// Generated Jun 15, 2012 8:41:06 AM by Hibernate Tools 3.4.0.CR1

import org.codehaus.jackson.annotate.JsonIgnore;

import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Session generated by hbm2java
 */
@Entity
@Table(name = "session", catalog = "onslyde")
public class Session implements java.io.Serializable {

	private Integer id;
	private User user;
	private String sessionName;
	private String sessionCode;
	private Date start;
	private Date end;
	private Date created;
	private Set<SlideGroup> slideGroups = new HashSet<SlideGroup>(0);

	public Session() {
	}

	public Session(User user, String sessionName, String sessionCode,
			Date start, Date end, Date created) {
		this.user = user;
		this.sessionName = sessionName;
		this.sessionCode = sessionCode;
		this.start = start;
		this.end = end;
		this.created = created;
	}

	public Session(User user, String sessionName, String sessionCode,
			Date start, Date end, Date created, Set<SlideGroup> slideGroups) {
		this.user = user;
		this.sessionName = sessionName;
		this.sessionCode = sessionCode;
		this.start = start;
		this.end = end;
		this.created = created;
		this.slideGroups = slideGroups;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

    @JsonIgnore
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "user_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "session_name", nullable = false)
	public String getSessionName() {
		return this.sessionName;
	}

	public void setSessionName(String sessionName) {
		this.sessionName = sessionName;
	}

	@Column(name = "session_code", nullable = false, length = 15)
	public String getSessionCode() {
		return this.sessionCode;
	}

	public void setSessionCode(String sessionCode) {
		this.sessionCode = sessionCode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "start", nullable = false, length = 19)
	public Date getStart() {
		return this.start;
	}

	public void setStart(Date start) {
		this.start = start;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "end", nullable = true, length = 19)
	public Date getEnd() {
		return this.end;
	}

	public void setEnd(Date end) {
		this.end = end;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 19)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "session")
	public Set<SlideGroup> getSlideGroups() {
		return this.slideGroups;
	}

	public void setSlideGroups(Set<SlideGroup> slideGroups) {
		this.slideGroups = slideGroups;
	}

}
