package com.onslyde.domain;

// Generated May 15, 2012 3:25:29 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Session generated by hbm2java
 */
@Entity
@Table(name = "session", catalog = "onslyde")
public class Session implements java.io.Serializable {

	private Integer id;
	private User user;
	private String sessionName;
	private String sessionCode;
	private Set<SlideGroup> slideGroups = new HashSet<SlideGroup>(0);

	public Session() {
	}

	public Session(User user, String sessionName, String sessionCode) {
		this.user = user;
		this.sessionName = sessionName;
		this.sessionCode = sessionCode;
	}

	public Session(User user, String sessionName, String sessionCode,
			Set<SlideGroup> slideGroups) {
		this.user = user;
		this.sessionName = sessionName;
		this.sessionCode = sessionCode;
		this.slideGroups = slideGroups;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "session_name", nullable = false)
	public String getSessionName() {
		return this.sessionName;
	}

	public void setSessionName(String sessionName) {
		this.sessionName = sessionName;
	}

	@Column(name = "session_code", nullable = false, length = 15)
	public String getSessionCode() {
		return this.sessionCode;
	}

	public void setSessionCode(String sessionCode) {
		this.sessionCode = sessionCode;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "session")
	public Set<SlideGroup> getSlideGroups() {
		return this.slideGroups;
	}

	public void setSlideGroups(Set<SlideGroup> slideGroups) {
		this.slideGroups = slideGroups;
	}

}
