package com.onslyde.domain;

// Generated May 15, 2012 3:25:29 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * SlideGroupVotes generated by hbm2java
 */
@Entity
@Table(name = "slide_group_votes", catalog = "onslyde")
public class SlideGroupVotes implements java.io.Serializable {

	private int id;
	private SlideGroupOptions slideGroupOptions;
	private SlideGroup slideGroup;
	private Attendee attendee;

	public SlideGroupVotes() {
	}

	public SlideGroupVotes(int id, SlideGroupOptions slideGroupOptions,
			SlideGroup slideGroup, Attendee attendee) {
		this.id = id;
		this.slideGroupOptions = slideGroupOptions;
		this.slideGroup = slideGroup;
		this.attendee = attendee;
	}

	@Id
    @GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "option_id", nullable = false)
	public SlideGroupOptions getSlideGroupOptions() {
		return this.slideGroupOptions;
	}

	public void setSlideGroupOptions(SlideGroupOptions slideGroupOptions) {
		this.slideGroupOptions = slideGroupOptions;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "slide_group_id", nullable = false)
	public SlideGroup getSlideGroup() {
		return this.slideGroup;
	}

	public void setSlideGroup(SlideGroup slideGroup) {
		this.slideGroup = slideGroup;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "attendee_id", nullable = false)
	public Attendee getAttendee() {
		return this.attendee;
	}

	public void setAttendee(Attendee attendee) {
		this.attendee = attendee;
	}

}
