package com.onslyde.domain;

// Generated Jun 15, 2012 8:41:06 AM by Hibernate Tools 3.4.0.CR1

import org.codehaus.jackson.annotate.JsonIgnore;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SlideGroupOptions generated by hbm2java
 */
@Entity
@Table(name = "slide_group_options", catalog = "onslyde")
public class SlideGroupOptions implements java.io.Serializable {

	private Integer id;
	private SlideGroup slideGroup;
	private String name;
	private String value;
	private Set<SlideGroupVotes> slideGroupVoteses = new HashSet<SlideGroupVotes>(
			0);

	public SlideGroupOptions() {
	}

	public SlideGroupOptions(SlideGroup slideGroup, String name) {
		this.slideGroup = slideGroup;
		this.name = name;
	}

	public SlideGroupOptions(SlideGroup slideGroup, String name, String value,
			Set<SlideGroupVotes> slideGroupVoteses) {
		this.slideGroup = slideGroup;
		this.name = name;
		this.value = value;
		this.slideGroupVoteses = slideGroupVoteses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

    @JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "slide_group_id", nullable = false)
	public SlideGroup getSlideGroup() {
		return this.slideGroup;
	}

	public void setSlideGroup(SlideGroup slideGroup) {
		this.slideGroup = slideGroup;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "value")
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

    @JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "slideGroupOptions")
	public Set<SlideGroupVotes> getSlideGroupVoteses() {
		return this.slideGroupVoteses;
	}

	public void setSlideGroupVoteses(Set<SlideGroupVotes> slideGroupVoteses) {
		this.slideGroupVoteses = slideGroupVoteses;
	}

}
