package com.onslyde.domain;

// Generated Jun 15, 2012 8:41:06 AM by Hibernate Tools 3.4.0.CR1

import org.codehaus.jackson.annotate.JsonIgnore;

import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

/**
 * Slide generated by hbm2java
 */
@Entity
@Table(name = "slide", catalog = "onslyde")
public class Slide implements java.io.Serializable {

	private Integer id;
    private Session session;
	private String name;
	private int slideIndex;
    private Set<SlideVotes> slideVoteses = new HashSet<SlideVotes>(
            0);
    private Set<SlideOptions> slideOptionses = new HashSet<SlideOptions>(
            0);

	public Slide() {
	}

	public Slide(Session session, int slideIndex) {
        this.session = session;
		this.slideIndex = slideIndex;
	}

	public Slide(Session session, String name, int slideIndex,
                 Set<SlideVotes> slideVoteses,
                 Set<SlideOptions> slideOptionses) {
        this.session = session;
		this.name = name;
		this.slideIndex = slideIndex;
        this.slideVoteses = slideVoteses;
        this.slideOptionses = slideOptionses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

    @JsonIgnore
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "session_id", nullable = false)
    public Session getSession() {
        return this.session;
    }

    public void setSession(Session session) {
        this.session = session;
    }



	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "slide_index", nullable = false)
	public int getSlideIndex() {
		return this.slideIndex;
	}

	public void setSlideIndex(int slideIndex) {
		this.slideIndex = slideIndex;
	}

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "slide")
    public Set<SlideVotes> getSlideVoteses() {
        return this.slideVoteses;
    }

    public void setSlideVoteses(Set<SlideVotes> slideVoteses) {
        this.slideVoteses = slideVoteses;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "slide")
    public Set<SlideOptions> getSlideOptionses() {
        return this.slideOptionses;
    }

    public void setSlideOptionses(
            Set<SlideOptions> slideOptionses) {
        this.slideOptionses = slideOptionses;
    }

}
