package com.onslyde.domain;

// Generated Jun 15, 2012 8:41:06 AM by Hibernate Tools 3.4.0.CR1

import org.codehaus.jackson.annotate.JsonIgnore;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SlideGroupVotes generated by hbm2java
 */
@Entity
@Table(name = "slide_group_votes", catalog = "onslyde")
public class SlideGroupVotes implements java.io.Serializable {

	private Integer id;
	private SlideGroupOptions slideGroupOptions;
	private SlideGroup slideGroup;
	private Attendee attendee;
	private Date voteTime;

	public SlideGroupVotes() {
	}

	public SlideGroupVotes(SlideGroupOptions slideGroupOptions,
			SlideGroup slideGroup, Attendee attendee, Date voteTime) {
		this.slideGroupOptions = slideGroupOptions;
		this.slideGroup = slideGroup;
		this.attendee = attendee;
		this.voteTime = voteTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "option_id", nullable = false)
	public SlideGroupOptions getSlideGroupOptions() {
		return this.slideGroupOptions;
	}

	public void setSlideGroupOptions(SlideGroupOptions slideGroupOptions) {
		this.slideGroupOptions = slideGroupOptions;
	}

    @JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "slide_group_id", nullable = false)
	public SlideGroup getSlideGroup() {
		return this.slideGroup;
	}

	public void setSlideGroup(SlideGroup slideGroup) {
		this.slideGroup = slideGroup;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "attendee_id", nullable = false)
	public Attendee getAttendee() {
		return this.attendee;
	}

	public void setAttendee(Attendee attendee) {
		this.attendee = attendee;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "vote_time", nullable = false, length = 19)
	public Date getVoteTime() {
		return this.voteTime;
	}

	public void setVoteTime(Date voteTime) {
		this.voteTime = voteTime;
	}

}
