package com.onslyde.domain;

// Generated Jun 15, 2012 8:41:06 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Slide generated by hbm2java
 */
@Entity
@Table(name = "slide", catalog = "onslyde")
public class Slide implements java.io.Serializable {

	private Integer id;
	private SlideGroup slideGroup;
	private String name;
	private int slideIndex;

	public Slide() {
	}

	public Slide(SlideGroup slideGroup, int slideIndex) {
		this.slideGroup = slideGroup;
		this.slideIndex = slideIndex;
	}

	public Slide(SlideGroup slideGroup, String name, int slideIndex) {
		this.slideGroup = slideGroup;
		this.name = name;
		this.slideIndex = slideIndex;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "slide_group_id", nullable = false)
	public SlideGroup getSlideGroup() {
		return this.slideGroup;
	}

	public void setSlideGroup(SlideGroup slideGroup) {
		this.slideGroup = slideGroup;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "slide_index", nullable = false)
	public int getSlideIndex() {
		return this.slideIndex;
	}

	public void setSlideIndex(int slideIndex) {
		this.slideIndex = slideIndex;
	}

}
