package com.onslyde.domain;

// Generated Jun 15, 2012 8:41:06 AM by Hibernate Tools 3.4.0.CR1

import org.codehaus.jackson.annotate.JsonIgnore;

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * SlideOptions generated by hbm2java
 */
@Entity
@Table(name = "slide_options", catalog = "onslyde")
public class SlideOptions implements java.io.Serializable {

	private Integer id;
	private Slide slide;
	private String name;
	private String value;
	private Set<SlideVotes> slideVoteses = new HashSet<SlideVotes>(
			0);

	public SlideOptions() {
	}

	public SlideOptions(Slide slide, String name) {
		this.slide = slide;
		this.name = name;
	}

	public SlideOptions(Slide slide, String name, String value,
                        Set<SlideVotes> slideVoteses) {
		this.slide = slide;
		this.name = name;
		this.value = value;
		this.slideVoteses = slideVoteses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

    @JsonIgnore
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "slide_id", nullable = false)
	public Slide getSlide() {
		return this.slide;
	}

	public void setSlide(Slide slide) {
		this.slide = slide;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "value")
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

    @JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "slideOptions")
	public Set<SlideVotes> getSlideVoteses() {
		return this.slideVoteses;
	}

	public void setSlideVoteses(Set<SlideVotes> slideVoteses) {
		this.slideVoteses = slideVoteses;
	}

}
