package com.onslyde.domain;

// Generated May 15, 2012 3:25:29 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * SlideGroupOptions generated by hbm2java
 */
@Entity
@Table(name = "slide_group_options", catalog = "onslyde")
public class SlideGroupOptions implements java.io.Serializable {

	private int id;
	private SlideGroup slideGroup;
	private String name;
	private String value;
	private Set<SlideGroupVotes> slideGroupVoteses = new HashSet<SlideGroupVotes>(
			0);

	public SlideGroupOptions() {
	}

	public SlideGroupOptions(int id, SlideGroup slideGroup, String name) {
		this.id = id;
		this.slideGroup = slideGroup;
		this.name = name;
	}

	public SlideGroupOptions(int id, SlideGroup slideGroup, String name,
			String value, Set<SlideGroupVotes> slideGroupVoteses) {
		this.id = id;
		this.slideGroup = slideGroup;
		this.name = name;
		this.value = value;
		this.slideGroupVoteses = slideGroupVoteses;
	}

	@Id
    @GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "slide_group_id", nullable = false)
	public SlideGroup getSlideGroup() {
		return this.slideGroup;
	}

	public void setSlideGroup(SlideGroup slideGroup) {
		this.slideGroup = slideGroup;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "value")
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "slideGroupOptions")
	public Set<SlideGroupVotes> getSlideGroupVoteses() {
		return this.slideGroupVoteses;
	}

	public void setSlideGroupVoteses(Set<SlideGroupVotes> slideGroupVoteses) {
		this.slideGroupVoteses = slideGroupVoteses;
	}

}
