package com.onslyde.domain;

// Generated May 15, 2012 3:25:29 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * SlideGroup generated by hbm2java
 */
@Entity
@Table(name = "slide_group", catalog = "onslyde")
public class SlideGroup implements java.io.Serializable {

	private int id;
	private Session session;
	private String groupName;
	private Set<Slide> slides = new HashSet<Slide>(0);
	private Set<SlideGroupVotes> slideGroupVoteses = new HashSet<SlideGroupVotes>(
			0);
	private Set<SlideGroupOptions> slideGroupOptionses = new HashSet<SlideGroupOptions>(
			0);

	public SlideGroup() {
	}

	public SlideGroup(int id, Session session, String groupName) {
		this.id = id;
		this.session = session;
		this.groupName = groupName;
	}

	public SlideGroup(int id, Session session, String groupName,
			Set<Slide> slides, Set<SlideGroupVotes> slideGroupVoteses,
			Set<SlideGroupOptions> slideGroupOptionses) {
		this.id = id;
		this.session = session;
		this.groupName = groupName;
		this.slides = slides;
		this.slideGroupVoteses = slideGroupVoteses;
		this.slideGroupOptionses = slideGroupOptionses;
	}

	@Id
    @GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "session_id", nullable = false)
	public Session getSession() {
		return this.session;
	}

	public void setSession(Session session) {
		this.session = session;
	}

	@Column(name = "group_name", nullable = false)
	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "slideGroup")
	public Set<Slide> getSlides() {
		return this.slides;
	}

	public void setSlides(Set<Slide> slides) {
		this.slides = slides;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "slideGroup")
	public Set<SlideGroupVotes> getSlideGroupVoteses() {
		return this.slideGroupVoteses;
	}

	public void setSlideGroupVoteses(Set<SlideGroupVotes> slideGroupVoteses) {
		this.slideGroupVoteses = slideGroupVoteses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "slideGroup")
	public Set<SlideGroupOptions> getSlideGroupOptionses() {
		return this.slideGroupOptionses;
	}

	public void setSlideGroupOptionses(
			Set<SlideGroupOptions> slideGroupOptionses) {
		this.slideGroupOptionses = slideGroupOptionses;
	}

}
