package com.onslyde.domain;

// Generated Jun 15, 2012 8:41:06 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;
import java.util.Date;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "onslyde")
public class User implements java.io.Serializable {

	private Integer id;
	private String fullName;
	private String email;
	private String password;
  private String saltedPassword;
	private Date created;
//	private Set<Session> sessions = new HashSet<Session>(0);

	public User() {
	}

	public User(String fullName, String email, String password, Date created, String saltedPassword) {
		this.fullName = fullName;
		this.email = email;
		this.password = password;
		this.created = created;
    this.saltedPassword = saltedPassword;
	}


	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "full_name", nullable = false)
	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	@Column(name = "email", nullable = false)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "password", nullable = true)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

  @Column(name = "salted_password", nullable = false)
  public String getSaltedPassword() { return this.saltedPassword; }

  public void setSaltedPassword(String saltedPassword) { this.saltedPassword = saltedPassword; }

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 19)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

//	@OneToMany(fetch = FetchType.EAGER, mappedBy = "user")
//	public Set<Session> getSessions() {
//		return this.sessions;
//	}
//
//	public void setSessions(Set<Session> sessions) {
//		this.sessions = sessions;
//	}

}
